//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaiPower.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessageServiceDBEntities : DbContext
    {
        public MessageServiceDBEntities()
            : base("name=MessageServiceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblSys> tblSys { get; set; }
        public virtual DbSet<tblTokenUpdateLog> tblTokenUpdateLog { get; set; }
        public virtual DbSet<tblMessageLog> tblMessageLog { get; set; }
        public virtual DbSet<tblSMSLog> tblSMSLog { get; set; }
    }
}
