//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaiPower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSys
    {
        public int seq { get; set; }
        public string redirect_uri { get; set; }
        public string client_id { get; set; }
        public string secrete { get; set; }
        public string iii_uri { get; set; }
    }
}
